FROM python:3.12-slim

WORKDIR /workspace

ADD requirements.txt requirements-dev.txt ./

RUN python3 -m venv /app/env && \
    /app/env/bin/pip install --upgrade pip && \
    /app/env/bin/pip install -U -r requirements-dev.txt

ADD boarding_pass_service ./boarding_pass_service
ADD pyproject.toml ./
COPY tests ./tests
COPY test_data ./test_data

ADD conf /app/conf/

RUN chmod 777 /workspace
RUN chmod 777 /app
RUN chmod -R 777 /app/conf
RUN chmod -R 777 /workspace/tests


CMD ["/app/env/bin/python3", "-m", "pytest", "-v", "tests"]
