BEGIN;

DROP TABLE IF EXISTS boarding_pass.boarding_pass_legs CASCADE;
DROP TABLE IF EXISTS boarding_pass.boarding_passes CASCADE;


CREATE TABLE boarding_pass.boarding_passes (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    parsed_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    passenger_name      VARCHAR(64),
    -- raw BCBP payload, so a pass can be re-decoded if the mapping ever changes
    raw_barcode         TEXT NOT NULL
);

CREATE INDEX boarding_passes_parsed_at ON boarding_pass.boarding_passes (parsed_at DESC);
CREATE INDEX boarding_passes_passenger_name ON boarding_pass.boarding_passes (lower(passenger_name));


CREATE TABLE boarding_pass.boarding_pass_legs (
    id                          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    boarding_pass_id            UUID NOT NULL REFERENCES boarding_pass.boarding_passes (id) ON DELETE CASCADE,
    leg_index                   INT NOT NULL,

    booking_reference           VARCHAR(16),
    airline_code                VARCHAR(4),
    flight_number               VARCHAR(8),
    julian_date                 INT,
    cabin_class                 VARCHAR(16),
    seat                        VARCHAR(8),
    passenger_status            VARCHAR(4),

    origin_code                 VARCHAR(4),
    origin_airport_name         VARCHAR(128),
    origin_city_name            VARCHAR(128),
    origin_country              VARCHAR(128),

    destination_code            VARCHAR(4),
    destination_airport_name    VARCHAR(128),
    destination_city_name       VARCHAR(128),
    destination_country         VARCHAR(128)
);

CREATE INDEX boarding_pass_legs_boarding_pass_id ON boarding_pass.boarding_pass_legs (boarding_pass_id);
CREATE INDEX boarding_pass_legs_airline_code ON boarding_pass.boarding_pass_legs (airline_code);
CREATE UNIQUE INDEX boarding_pass_legs_index ON boarding_pass.boarding_pass_legs (boarding_pass_id, leg_index);


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA boarding_pass TO boarding_pass;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA boarding_pass TO boarding_pass;

COMMIT;
